<a href="https://colab.research.google.com/github/5ury4pr454th/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Madagascar problem

In [1]:
import numpy as np

In [2]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [3]:
# 4x3 . 3x1 = 4x1

In [4]:
y = np.matmul(A,x) - 4.0

In [5]:
Z = np.hstack((A,y))

In [6]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [7]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [8]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]


In [12]:
def covid_risk(A, x):
  return (RankArray(A, x).T[-1]>0)

covid_risk(A, x)

array([False, False,  True,  True])

In [13]:
for _, person in enumerate(covid_risk(A, x)):
  print(f"Person {_} is {'' if person == True else 'not'} at risk")

Person 0 is not at risk
Person 1 is not at risk
Person 2 is  at risk
Person 3 is  at risk
